# Generated by Django 5.1.7 on 2025-04-22 15:45

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cabang',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.UUIDField(auto_created=True, default=uuid.uuid4)),
                ('nama_toko', models.CharField(default='Nama Toko', max_length=20)),
                ('nama_cabang', models.CharField(default='Cabang1', max_length=15)),
                ('alamat_toko', models.CharField(default='Jalan...', max_length=30)),
                ('telpon', models.CharField(default='081234567890', max_length=15)),
                ('keterangan', models.CharField(default='', max_length=200)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='UploadBarang',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='file_barang')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cabang', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='cabang_user', to='stock.cabang')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Barang',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('barcode', models.CharField(default='0', max_length=100)),
                ('nama', models.CharField(max_length=200)),
                ('satuan', models.CharField(choices=[('PCS', 'PCS'), ('PACK', 'PACK')], default='PCS', max_length=20)),
                ('stok', models.IntegerField(default=0)),
                ('harga_ecer', models.IntegerField(default=0)),
                ('harga_grosir', models.IntegerField(default=0)),
                ('min_beli_grosir', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL)),
                ('cabang', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='cabang_toko', to='stock.cabang')),
            ],
            options={
                'unique_together': {('cabang', 'barcode', 'nama')},
            },
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('customer', models.UUIDField(auto_created=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nama', models.CharField(default='', max_length=200)),
                ('handphone', models.CharField(default='081', max_length=20)),
                ('alamat', models.CharField(default='', max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('nama', 'handphone')},
            },
        ),
    ]
