# Generated by Django 5.1.7 on 2025-04-03 16:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='customer',
            unique_together={('nama', 'handphone')},
        ),
    ]
