# Generated by Django 5.1.7 on 2025-04-23 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='barang',
            name='jumlah_dibeli',
            field=models.BigIntegerField(default=0),
        ),
    ]
