# Generated by Django 5.1.7 on 2025-04-27 19:08

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0002_barang_jumlah_dibeli'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='uploadbarang',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='uploadbarang',
            name='file',
        ),
        migrations.AddField(
            model_name='uploadbarang',
            name='cabang',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.RESTRICT, related_name='cabang', to='stock.cabang'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='uploadbarang',
            name='id_upload',
            field=models.UUIDField(auto_created=True, default=uuid.uuid4, editable=False),
        ),
        migrations.AddField(
            model_name='uploadbarang',
            name='user',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='UploadBarangList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('barcode', models.CharField(default='0', max_length=100)),
                ('nama', models.CharField(max_length=200)),
                ('satuan', models.CharField(choices=[('PCS', 'PCS'), ('PACK', 'PACK')], default='PCS', max_length=20)),
                ('stok', models.IntegerField(default=0)),
                ('harga_ecer', models.IntegerField(default=0)),
                ('harga_grosir', models.IntegerField(default=0)),
                ('min_beli_grosir', models.IntegerField(default=0)),
                ('upload_barang', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stock.uploadbarang')),
            ],
        ),
    ]
