# Generated by Django 5.1.7 on 2025-04-27 19:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0003_remove_uploadbarang_created_by_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='barang',
            unique_together={('cabang', 'barcode')},
        ),
    ]
