# Generated by Django 5.1.7 on 2025-04-29 09:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0005_logtransaksi'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logtransaksi',
            name='cabang',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.RESTRICT, to='stock.cabang'),
        ),
    ]
