# Generated by Django 5.1.7 on 2025-04-29 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0008_userprofile_foto'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='nama_lengkap',
            field=models.CharField(default='', max_length=30),
        ),
    ]
