# Generated by Django 5.1.7 on 2025-04-30 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0009_userprofile_nama_lengkap'),
    ]

    operations = [
        migrations.AddField(
            model_name='cabang',
            name='prefix',
            field=models.CharField(default='', max_length=5),
        ),
        migrations.AddField(
            model_name='cabang',
            name='prefix_count',
            field=models.IntegerField(default=0),
        ),
    ]
