# Generated by Django 5.1.7 on 2025-04-30 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0010_cabang_prefix_cabang_prefix_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cabang',
            name='prefix',
            field=models.CharField(default='qawc', max_length=5),
        ),
    ]
