# Generated by Django 5.1.7 on 2025-04-30 06:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0011_alter_cabang_prefix'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cabang',
            name='prefix',
        ),
    ]
