# Generated by Django 5.1.7 on 2025-04-30 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0012_remove_cabang_prefix'),
    ]

    operations = [
        migrations.AddField(
            model_name='cabang',
            name='prefix',
            field=models.CharField(default='onwi', max_length=5),
        ),
    ]
