# Generated by Django 5.1.7 on 2025-04-30 08:02

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0013_cabang_prefix'),
    ]

    operations = [
        migrations.CreateModel(
            name='DaftarPaket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paket', models.UUIDField(auto_created=True, default=uuid.uuid4, editable=False)),
                ('max_transaksi', models.IntegerField(default=0)),
                ('max_user_login', models.IntegerField(default=0)),
                ('is_download_transaksi', models.BooleanField(default=True)),
                ('is_tambah_barang', models.BooleanField(default=True)),
                ('is_download_barang', models.BooleanField(default=True)),
                ('is_laporan_transaksi', models.BooleanField(default=True)),
                ('harga', models.PositiveIntegerField(default=0)),
                ('disc', models.IntegerField(default=0)),
            ],
        ),
        migrations.AlterField(
            model_name='cabang',
            name='prefix',
            field=models.CharField(default='cvug', max_length=5),
        ),
        migrations.CreateModel(
            name='PaketCabang',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('expired', models.DateTimeField(null=True)),
                ('is_active', models.BooleanField(default=False)),
                ('cabang', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='Cabang_Paket', to='stock.cabang')),
                ('paket', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='paket_cabang', to='stock.daftarpaket')),
            ],
        ),
    ]
