# Generated by Django 5.1.7 on 2025-04-30 08:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0014_daftarpaket_alter_cabang_prefix_paketcabang'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='daftarpaket',
            old_name='harga',
            new_name='harga_per_bulan',
        ),
        migrations.AddField(
            model_name='daftarpaket',
            name='harga_per_dua_tahun',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='daftarpaket',
            name='harga_per_enam_bulan',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='daftarpaket',
            name='harga_per_tahun',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='daftarpaket',
            name='harga_per_tiga_bulan',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='cabang',
            name='prefix',
            field=models.CharField(default='sogt', max_length=5),
        ),
        migrations.AlterField(
            model_name='paketcabang',
            name='cabang',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.RESTRICT, related_name='Cabang_Paket', to='stock.cabang'),
        ),
        migrations.AlterField(
            model_name='paketcabang',
            name='paket',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.RESTRICT, related_name='paket_cabang', to='stock.daftarpaket'),
        ),
        migrations.CreateModel(
            name='Pembayaran',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('harga', models.PositiveIntegerField(default=0)),
                ('langganan', models.IntegerField(choices=[('1', 'Bulanan'), ('3', 'Per Tiga Bulanan'), ('6', 'Per Semester'), ('12', 'Per 1 Tahun'), ('24', 'Per 2 Tahun')], default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expired_at', models.DateTimeField(null=True)),
                ('paket', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='stock.daftarpaket')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
