# Generated by Django 5.1.7 on 2025-04-30 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0015_rename_harga_daftarpaket_harga_per_bulan_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='daftar_paket',
            field=models.CharField(default='', max_length=1000),
        ),
        migrations.AlterField(
            model_name='cabang',
            name='prefix',
            field=models.CharField(default='cmrl', max_length=5),
        ),
    ]
