# Generated by Django 5.2 on 2025-04-30 23:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0016_userprofile_daftar_paket_alter_cabang_prefix'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='daftar_paket',
        ),
        migrations.AddField(
            model_name='pembayaran',
            name='midtrans_token',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='cabang',
            name='prefix',
            field=models.CharField(default='aarp', max_length=5),
        ),
        migrations.CreateModel(
            name='UserPaket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('paket', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='daftar_paket', to='stock.daftarpaket')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'paket')},
            },
        ),
    ]
