# Generated by Django 5.2 on 2025-05-01 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0017_remove_userprofile_daftar_paket_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cabang',
            name='prefix',
            field=models.CharField(default='qsnt', max_length=5),
        ),
    ]
