# Generated by Django 5.2 on 2025-05-01 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0018_alter_cabang_prefix_alter_pembayaran_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pembayaran',
            name='expired_at',
        ),
        migrations.RemoveField(
            model_name='pembayaran',
            name='langganan',
        ),
        migrations.AddField(
            model_name='pembayaran',
            name='jumlah_bulan',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='cabang',
            name='prefix',
            field=models.CharField(default='hxpt', max_length=5),
        ),
    ]
