# Generated by Django 5.2 on 2025-05-01 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0019_remove_pembayaran_expired_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='daftarpaket',
            name='nama',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='cabang',
            name='prefix',
            field=models.CharField(default='twqg', max_length=5),
        ),
    ]
