# Generated by Django 5.2 on 2025-05-01 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0020_daftarpaket_nama_alter_cabang_prefix'),
    ]

    operations = [
        migrations.AddField(
            model_name='cabang',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='cabang',
            name='prefix',
            field=models.CharField(default='gpsj', max_length=5),
        ),
    ]
