# Generated by Django 5.2 on 2025-05-01 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0021_cabang_email_alter_cabang_prefix'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cabang',
            name='prefix',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
    ]
