# Generated by Django 5.2 on 2025-05-01 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0022_alter_cabang_prefix'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cabang',
            name='email',
            field=models.EmailField(blank=True, max_length=200, null=True),
        ),
    ]
