# Generated by Django 5.1.7 on 2025-05-02 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0023_alter_cabang_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='cabang',
            name='kuota_transaksi',
            field=models.IntegerField(default=99999999),
        ),
    ]
