# Generated by Django 5.1.7 on 2025-05-02 21:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0024_cabang_kuota_transaksi'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cabang',
            name='prefix_count',
        ),
    ]
