# Generated by Django 5.1.7 on 2025-05-03 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0025_remove_cabang_prefix_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='cabang',
            name='jumlah_kasir',
            field=models.IntegerField(default=0),
        ),
    ]
