# Generated by Django 5.1.7 on 2025-05-03 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0026_cabang_jumlah_kasir'),
    ]

    operations = [
        migrations.AddField(
            model_name='barang',
            name='harga_beli',
            field=models.IntegerField(default=0),
        ),
    ]
