# Generated by Django 5.1.7 on 2025-05-03 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0027_barang_harga_beli'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadbaranglist',
            name='harga_beli',
            field=models.IntegerField(default=0),
        ),
    ]
