# Generated by Django 5.1.7 on 2025-05-03 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0028_uploadbaranglist_harga_beli'),
    ]

    operations = [
        migrations.AddField(
            model_name='cabang',
            name='lisensi_expired',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cabang',
            name='lisensi_grace',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
