# Generated by Django 5.1.7 on 2025-05-05 15:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0029_cabang_lisensi_expired_cabang_lisensi_grace'),
    ]

    operations = [
        migrations.AddField(
            model_name='cabang',
            name='paket',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='paket_cabang', to='stock.daftarpaket'),
        ),
        migrations.DeleteModel(
            name='PaketCabang',
        ),
    ]
