# Generated by Django 5.1.7 on 2025-05-05 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0030_cabang_paket_delete_paketcabang'),
    ]

    operations = [
        migrations.AddField(
            model_name='cabang',
            name='last_update_kuota',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
