# Generated by Django 5.1.7 on 2025-05-05 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0031_cabang_last_update_kuota'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='daftarpaket',
            name='is_download_barang',
        ),
        migrations.RemoveField(
            model_name='daftarpaket',
            name='is_download_transaksi',
        ),
        migrations.RemoveField(
            model_name='daftarpaket',
            name='is_laporan_transaksi',
        ),
        migrations.RemoveField(
            model_name='daftarpaket',
            name='is_tambah_barang',
        ),
        migrations.AddField(
            model_name='barang',
            name='keterangan',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='cabang',
            name='keterangan',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
    ]
