# Generated by Django 5.1.8 on 2025-05-10 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0032_remove_daftarpaket_is_download_barang_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cabang',
            name='kode_referal',
            field=models.CharField(default='', max_length=5, verbose_name='Diisi kode prefix user'),
            preserve_default=False,
        ),
    ]
