# Generated by Django 5.2.1 on 2025-05-14 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0033_cabang_kode_referal'),
    ]

    operations = [
        migrations.AddField(
            model_name='cabang',
            name='no_nota',
            field=models.IntegerField(default=1),
        ),
    ]
