# Generated by Django 5.2.1 on 2025-05-15 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0034_cabang_no_nota'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cabang',
            name='no_nota',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
    ]
