# Generated by Django 5.2.1 on 2025-05-15 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0035_alter_cabang_no_nota'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cabang',
            name='kode_referal',
            field=models.CharField(blank=True, max_length=5, null=True, verbose_name='Diisi kode prefix user'),
        ),
    ]
