# Generated by Django 5.2.1 on 2025-05-15 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0036_alter_cabang_kode_referal'),
    ]

    operations = [
        migrations.AddField(
            model_name='cabang',
            name='wallet',
            field=models.PositiveBigIntegerField(default=0),
        ),
    ]
