# Generated by Django 5.2.1 on 2025-05-16 00:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0037_cabang_wallet'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cabang',
            name='no_nota',
        ),
    ]
