# Generated by Django 5.2.1 on 2025-05-16 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0038_remove_cabang_no_nota'),
    ]

    operations = [
        migrations.AddField(
            model_name='cabang',
            name='no_nota',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
