# Generated by Django 5.2.1 on 2025-05-18 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0039_cabang_no_nota'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadbaranglist',
            name='keterangan',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
