# Generated by Django 5.2.1 on 2025-06-02 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0040_uploadbaranglist_keterangan_userprofile_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='is_admin',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='is_kasir',
            field=models.BooleanField(default=True),
        ),
    ]
