# Generated by Django 5.2.3 on 2026-05-30 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0041_userprofile_is_admin_userprofile_is_kasir'),
    ]

    operations = [
        migrations.AlterField(
            model_name='barang',
            name='barcode',
            field=models.CharField(default='0', max_length=100, verbose_name='Barcode (Bisa Menggunakan Scanner)'),
        ),
        migrations.AlterField(
            model_name='barang',
            name='harga_beli',
            field=models.IntegerField(default=0, verbose_name='Harga Pembelian (Modal+Pajak)'),
        ),
        migrations.AlterField(
            model_name='barang',
            name='harga_ecer',
            field=models.IntegerField(default=0, verbose_name='Harga Eceran (satuan)'),
        ),
        migrations.AlterField(
            model_name='barang',
            name='harga_grosir',
            field=models.IntegerField(default=0, verbose_name='Harga Grosir (bisa disamakan dengan harga ecer)'),
        ),
        migrations.AlterField(
            model_name='barang',
            name='keterangan',
            field=models.CharField(blank=True, default='', max_length=200, null=True, verbose_name='Keterangan Barang'),
        ),
        migrations.AlterField(
            model_name='barang',
            name='min_beli_grosir',
            field=models.IntegerField(default=0, verbose_name='Minimal pembelian untuk dihitung harga grosir'),
        ),
        migrations.AlterField(
            model_name='barang',
            name='nama',
            field=models.CharField(max_length=200, verbose_name='Nama Barang'),
        ),
        migrations.AlterField(
            model_name='barang',
            name='satuan',
            field=models.CharField(choices=[('PCS', 'PCS'), ('PACK', 'PACK')], default='PCS', max_length=20, verbose_name='Satuan (PACK atau PCS)'),
        ),
        migrations.AlterField(
            model_name='barang',
            name='stok',
            field=models.IntegerField(default=0, verbose_name='Jumlah Stok Awal'),
        ),
    ]
