# Generated by Django 5.2.3 on 2026-05-31 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0042_alter_barang_barcode_alter_barang_harga_beli_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cabang',
            name='kuota_transaksi',
            field=models.IntegerField(default=75),
        ),
    ]
