# Generated by Django 5.2.3 on 2026-06-03 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0046_cabang_is_email_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='daftarpaket',
            name='is_add_ons',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='daftarpaket',
            name='is_ceklist_barang',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='daftarpaket',
            name='is_pembayaran_tempo',
            field=models.BooleanField(default=False),
        ),
    ]
