# Generated by Django 6.0.6 on 2026-10-08 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0047_daftarpaket_fitur_tambahan'),
    ]

    operations = [
        migrations.AddField(
            model_name='logtransaksi',
            name='detail',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
