# Generated by Django 5.2.1 on 2025-05-12 15:58

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('stock', '0033_cabang_kode_referal'),
    ]

    operations = [
        migrations.CreateModel(
            name='Promo',
            fields=[
                ('id', models.UUIDField(auto_created=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nama', models.CharField(max_length=200)),
                ('disc', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('end_period', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('kuota', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='PromoUsed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('cabang', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='cabang_used', to='stock.cabang')),
                ('promo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='promo_master', to='promo.promo')),
            ],
        ),
    ]
