# Generated by Django 5.2.1 on 2025-05-12 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='promo',
            name='kode',
            field=models.SlugField(default='', max_length=20, unique=True),
            preserve_default=False,
        ),
    ]
