# Generated by Django 5.2.1 on 2025-05-14 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promo', '0002_promo_kode'),
    ]

    operations = [
        migrations.AddField(
            model_name='promo',
            name='is_tambah_kuota',
            field=models.BooleanField(default=False),
        ),
    ]
