# Generated by Django 5.2.1 on 2025-05-15 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promo', '0003_promo_is_tambah_kuota'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promo',
            name='is_tambah_kuota',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
