# Generated by Django 5.2.1 on 2025-05-15 23:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('promo', '0004_alter_promo_is_tambah_kuota'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='promo',
            name='is_tambah_kuota',
        ),
    ]
