# Generated by Django 5.2.1 on 2025-05-16 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promo', '0005_remove_promo_is_tambah_kuota'),
    ]

    operations = [
        migrations.AddField(
            model_name='promo',
            name='is_perpanjangan',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='promo',
            name='is_registrasi',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='promo',
            name='is_tambah_kuota',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='promo',
            name='is_upgrade_lisensi',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
