# Generated by Django 5.1.8 on 2025-05-10 08:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('stock', '0033_cabang_kode_referal'),
    ]

    operations = [
        migrations.CreateModel(
            name='TokoGetToko',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nilai', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_withdraw', models.BooleanField(default=True)),
                ('cabang', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='referal', to='stock.cabang')),
                ('paket', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='paketnya', to='stock.daftarpaket')),
                ('registrar', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='cabang_baru', to='stock.cabang')),
            ],
        ),
    ]
