# Generated by Django 5.2.3 on 2025-07-04 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MidtransPayment',
            fields=[
                ('id', models.CharField(default='', max_length=100, primary_key=True, serialize=False)),
                ('total', models.IntegerField(default=0)),
                ('kode_voucher', models.CharField(blank=True, max_length=100, null=True)),
                ('referal_point', models.IntegerField(default=0)),
                ('transaksi', models.CharField(default='', max_length=100)),
                ('jml_kuota', models.IntegerField(blank=True, default=0, null=True)),
                ('lisensi_expired', models.DateTimeField(blank=True, null=True)),
                ('is_success', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
