# Generated by Codex on 2026-05-22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PermintaanKonsultasi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=200)),
                ('jenis_permintaan', models.CharField(choices=[('konsultasi_gratis', 'Konsultasi Gratis'), ('demo_aplikasi', 'Demo Aplikasi')], default='konsultasi_gratis', max_length=50)),
                ('aplikasi_demo', models.CharField(blank=True, choices=[('jurnal_koperasi', 'Aplikasi Jurnal untuk Koperasi'), ('pos', 'Aplikasi Penjualan (POS)'), ('platform_baca', 'Aplikasi Platform Baca')], max_length=50, null=True)),
                ('keterangan', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
