# Generated by Django 5.2.3 on 2025-07-04 01:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0002_midtranspayment'),
        ('stock', '0042_alter_barang_barcode_alter_barang_harga_beli_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='midtranspayment',
            name='cabang',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='stock.cabang'),
        ),
    ]
