# Generated by Django 5.2.3 on 2026-05-31 13:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0002_permintaankonsultasi'),
        ('stock', '0042_alter_barang_barcode_alter_barang_harga_beli_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GaransiRefund',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jumlah_pembayaran', models.PositiveIntegerField(default=0)),
                ('jumlah_bulan', models.PositiveIntegerField(default=1)),
                ('tanggal_aktivasi', models.DateTimeField()),
                ('batas_pengajuan', models.DateTimeField()),
                ('status', models.CharField(choices=[('eligible', 'Belum diajukan'), ('diajukan_auto', 'Diajukan auto refund'), ('diajukan_mediasi', 'Diajukan mediasi'), ('disetujui', 'Disetujui'), ('ditolak', 'Ditolak'), ('dibayar', 'Sudah dibayar'), ('expired', 'Masa garansi berakhir')], default='eligible', max_length=30)),
                ('alur_pengajuan', models.CharField(blank=True, choices=[('auto_refund', 'Auto refund'), ('mediasi', 'Mediasi')], max_length=30, null=True)),
                ('alasan', models.TextField(blank=True, null=True)),
                ('jumlah_transaksi_saat_pengajuan', models.PositiveIntegerField(default=0)),
                ('requested_at', models.DateTimeField(blank=True, null=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('catatan_admin', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cabang', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='garansi_refund', to='stock.cabang')),
                ('paket', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='garansi_refund_paket', to='stock.daftarpaket')),
                ('processed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='refund_diproses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
