# Generated by Django 5.2.3 on 2025-07-04 02:15

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0003_midtranspayment_cabang'),
    ]

    operations = [
        migrations.AlterField(
            model_name='midtranspayment',
            name='id',
            field=models.UUIDField(auto_created=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
