# Generated by Django 5.2.3 on 2026-06-01 17:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('owner', '0008_toko_addon'),
        ('payment', '0003_garansirefund'),
        ('stock', '0046_cabang_is_email_verified'),
    ]

    operations = [
        migrations.CreateModel(
            name='TokoAddon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('addon_type', models.CharField(choices=[('barcode', 'Cetak Label Barcode'), ('nota_custom', 'Custom Template Nota'), ('akunting', 'Laporan Akunting Otomatis')], max_length=20)),
                ('status', models.CharField(choices=[('aktif', 'Aktif'), ('nonaktif', 'Tidak Aktif'), ('expired', 'Expired')], default='nonaktif', max_length=10)),
                ('activated_at', models.DateTimeField(blank=True, null=True)),
                ('expired_at', models.DateTimeField(blank=True, null=True)),
                ('harga_dibayar', models.PositiveIntegerField(default=0)),
                ('catatan_admin', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cabang', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='addons', to='stock.cabang')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='addons', to='owner.owner')),
            ],
            options={
                'unique_together': {('cabang', 'addon_type'), ('owner', 'addon_type')},
            },
        ),
    ]
