# Generated by Django 5.2.3 on 2026-06-03 16:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0004_toko_addon'),
        ('stock', '0046_cabang_is_email_verified'),
    ]

    operations = [
        migrations.CreateModel(
            name='AddonConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('addon_type', models.CharField(choices=[('barcode', 'Cetak Label Barcode'), ('nota_custom', 'Custom Template Nota'), ('akunting', 'Laporan Akunting Otomatis')], max_length=20)),
                ('config', models.JSONField(blank=True, default=dict)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cabang', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addon_configs', to='stock.cabang')),
            ],
            options={
                'unique_together': {('cabang', 'addon_type')},
            },
        ),
    ]
