# Generated by Django 5.2.3 on 2025-07-04 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0004_alter_midtranspayment_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='midtranspayment',
            name='midtrans_token',
            field=models.CharField(default='', max_length=100),
        ),
    ]
