# Generated by Django 5.2.3 on 2025-07-04 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0005_midtranspayment_midtrans_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='midtranspayment',
            name='alamat_toko',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='midtranspayment',
            name='email_toko',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='midtranspayment',
            name='kode_toko',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='midtranspayment',
            name='nama_cabang',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='midtranspayment',
            name='nama_toko',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='midtranspayment',
            name='password',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='midtranspayment',
            name='pemilik_toko',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='midtranspayment',
            name='telpon_toko',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
