# Generated by Django 5.2.3 on 2026-06-03 20:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('owner', '0008_toko_addon'),
        ('payment', '0006_pending_payment'),
        ('stock', '0047_daftarpaket_fitur_tambahan'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransaksiPembelian',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.CharField(max_length=120, unique=True)),
                ('tipe', models.CharField(choices=[('registrasi', 'Registrasi Paket'), ('upgrade', 'Upgrade/Perpanjangan Lisensi'), ('kuota', 'Tambah Kuota Transaksi'), ('addon', 'Aktivasi Add-on'), ('owner_upgrade', 'Upgrade Korporasi')], max_length=20)),
                ('keterangan', models.CharField(blank=True, max_length=200)),
                ('harga', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('cabang', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transaksi_pembelian', to='stock.cabang')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transaksi_pembelian', to='owner.owner')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
