# Generated by Django 5.2.3 on 2025-07-04 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0006_midtranspayment_alamat_toko_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='midtranspayment',
            name='jenis_paket',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='midtranspayment',
            name='lisensi_grace',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='midtranspayment',
            name='status_paket',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
