# Generated by Django 5.2.3 on 2025-07-04 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0007_midtranspayment_jenis_paket_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='midtranspayment',
            name='kode_referensi',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
