# Generated by Django 5.2.1 on 2025-05-29 08:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('stock', '0040_uploadbaranglist_keterangan_userprofile_is_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='Testimoni',
            fields=[
                ('id', models.UUIDField(auto_created=True, editable=False, primary_key=True, serialize=False)),
                ('testimoni', models.CharField(blank=True, max_length=200, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cabang', models.OneToOneField(on_delete=django.db.models.deletion.RESTRICT, to='stock.cabang')),
            ],
        ),
    ]
