# Generated by Django 5.2.1 on 2025-05-29 08:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0001_initial'),
        ('stock', '0040_uploadbaranglist_keterangan_userprofile_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testimoni',
            name='cabang',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='stock.cabang'),
        ),
        migrations.AlterField(
            model_name='testimoni',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='testimoni',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
