# Generated by Django 5.2.1 on 2025-05-29 08:17

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0002_alter_testimoni_cabang_alter_testimoni_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testimoni',
            name='id',
            field=models.UUIDField(auto_created=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
