# Generated by Django 5.2.1 on 2025-05-29 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0003_alter_testimoni_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='testimoni',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
    ]
