# Generated by Django 5.2.1 on 2025-06-03 09:40

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0004_testimoni_is_verified'),
        ('stock', '0041_userprofile_is_admin_userprofile_is_kasir'),
    ]

    operations = [
        migrations.CreateModel(
            name='GantiEmail',
            fields=[
                ('id', models.UUIDField(auto_created=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('expired', models.DateTimeField(blank=True, null=True)),
                ('clicked', models.BooleanField(default=False)),
                ('email_baru', models.CharField(blank=True, max_length=200, null=True)),
                ('cabang', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='stock.cabang')),
            ],
        ),
    ]
