# Generated by Django 5.2.1 on 2025-06-03 10:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0005_gantiemail'),
        ('stock', '0041_userprofile_is_admin_userprofile_is_kasir'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='gantiemail',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='user_konfirmasi', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='gantiemail',
            name='cabang',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='cabang_konfirmasi', to='stock.cabang'),
        ),
    ]
