# Generated by Django 5.2.3 on 2026-06-01 16:21

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0007_add_reset_password_token'),
        ('stock', '0046_cabang_is_email_verified'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailVerificationToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expired_at', models.DateTimeField()),
                ('cabang', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='email_token', to='stock.cabang')),
            ],
        ),
    ]
