# Generated by Django 5.2.3 on 2026-06-03 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0008_email_verification_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='testimoni',
            name='bonus_diberikan',
            field=models.BooleanField(default=False),
        ),
    ]
