# Generated by Django 5.2.3 on 2026-06-01 17:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('stock', '0046_cabang_is_email_verified'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApiKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(editable=False, max_length=64, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_used', models.DateTimeField(blank=True, null=True)),
                ('cabang', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='api_key', to='stock.cabang')),
            ],
        ),
        migrations.CreateModel(
            name='WebhookEndpoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(max_length=500)),
                ('event', models.CharField(choices=[('transaction.completed', 'Transaksi Selesai'), ('transaction.voided', 'Transaksi Void'), ('stock.low', 'Stok Rendah (< 5)')], max_length=30)),
                ('secret', models.CharField(editable=False, max_length=64)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('cabang', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='webhooks', to='stock.cabang')),
            ],
        ),
        migrations.CreateModel(
            name='WebhookLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.CharField(max_length=30)),
                ('payload', models.JSONField()),
                ('status', models.CharField(default='fail', max_length=10)),
                ('response_code', models.IntegerField(blank=True, null=True)),
                ('error', models.TextField(blank=True)),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('webhook', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='api.webhookendpoint')),
            ],
        ),
    ]
