# Generated by Django 5.1.7 on 2025-04-11 19:51

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('stock', '0004_alter_barang_created_at_alter_barang_updated_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Penjualan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nota', models.UUIDField(auto_created=True, default=uuid.uuid4, editable=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('items', models.IntegerField(default=0)),
                ('is_paid', models.BooleanField(default=False)),
                ('cabang', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='stock.cabang')),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='customer_penjualan', to='stock.customer')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='user_login', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PenjualanDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jumlah', models.IntegerField(default=0)),
                ('harga', models.BigIntegerField(blank=True, default=0, null=True)),
                ('total', models.BigIntegerField(blank=True, default=0, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('barang', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='stock.barang')),
                ('penjualan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pos.penjualan')),
            ],
            options={
                'unique_together': {('penjualan', 'barang')},
            },
        ),
        migrations.CreateModel(
            name='TotalPenjualan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tanggal', models.DateField(blank=True, null=True)),
                ('total', models.BigIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cabang', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='stock.cabang')),
            ],
            options={
                'unique_together': {('cabang', 'tanggal')},
            },
        ),
    ]
