# Generated by Django 5.2.1 on 2025-05-14 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='penjualan',
            name='no_nota',
            field=models.CharField(default=0, max_length=15),
            preserve_default=False,
        ),
    ]
