# Generated by Django 5.1.7 on 2025-04-11 19:56

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='penjualan',
            name='id',
        ),
        migrations.AlterField(
            model_name='penjualan',
            name='nota',
            field=models.UUIDField(auto_created=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
