# Generated by Django 5.2.1 on 2025-05-16 10:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0002_penjualan_no_nota'),
        ('stock', '0039_cabang_no_nota'),
    ]

    operations = [
        migrations.CreateModel(
            name='DetailWalet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keterangan', models.CharField(default='', max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('jumlah', models.PositiveIntegerField(default=0)),
                ('cabang', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='stock.cabang')),
            ],
        ),
    ]
