# Generated by Django 5.2.1 on 2025-05-16 10:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0003_detailwalet'),
        ('stock', '0039_cabang_no_nota'),
    ]

    operations = [
        migrations.AddField(
            model_name='detailwalet',
            name='cabang_referensi',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='cabang_referensi', to='stock.cabang'),
        ),
        migrations.AlterField(
            model_name='detailwalet',
            name='cabang',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='cabang_referal', to='stock.cabang'),
        ),
    ]
