# Generated by Django 5.2.1 on 2025-05-28 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0004_detailwalet_cabang_referensi_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='penjualandetail',
            name='is_open',
            field=models.BooleanField(default=False),
        ),
    ]
