# Generated by Django 5.2.1 on 2025-05-28 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0005_penjualandetail_is_open'),
    ]

    operations = [
        migrations.AddField(
            model_name='penjualandetail',
            name='harga_awal',
            field=models.BigIntegerField(blank=True, default=0, null=True),
        ),
    ]
