# Generated by Django 5.2.1 on 2025-05-30 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0006_penjualandetail_harga_awal'),
    ]

    operations = [
        migrations.AddField(
            model_name='penjualan',
            name='cetak_kuitansi',
            field=models.IntegerField(default=0),
        ),
    ]
