# Generated by Django 5.2.1 on 2025-05-30 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0007_penjualan_cetak_kuitansi'),
    ]

    operations = [
        migrations.AddField(
            model_name='penjualan',
            name='alasan_void',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='penjualan',
            name='is_void',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
