# Generated by Django 5.2.1 on 2025-05-15 11:05

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tutorial',
            fields=[
                ('id', models.UUIDField(auto_created=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('judul', models.CharField(default='', max_length=100)),
                ('artikel', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('view', models.IntegerField(default=0)),
                ('created_by', models.CharField(default='', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='TutorialComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.CharField(default='', max_length=200)),
                ('is_publish', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.CharField(default='', max_length=100)),
                ('email_creator', models.EmailField(default='', max_length=200)),
                ('tutorial', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='cara.tutorial')),
            ],
        ),
        migrations.CreateModel(
            name='TutorialImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='tutorial_image')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tutorial', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='cara.tutorial')),
            ],
        ),
    ]
